INSERT INTO users (username, password) VALUES ('user1', '$2b$10$.FzHPRlvtV1ZXY/EUsYGae9qCds4P8O08bp1WMB0NsALcqa/cXqfi');
INSERT INTO users (username, password) VALUES ('user2', '$2b$10$QSslCBJ3/hJe6wCcWKLmuOASS.UHfLDefJ5oRwIe2R7EyYpQLxVMS');
INSERT INTO products (name) VALUES ("popcorn");
INSERT INTO products (name) VALUES ("sliced cheese");
INSERT INTO products (name) VALUES ("walnut");
INSERT INTO products (name) VALUES ("nice black tea carrefour");
INSERT INTO products (name) VALUES ("real parmesan");
INSERT INTO products (name) VALUES ("sausage");
INSERT INTO products (name) VALUES ("carrot");
INSERT INTO products (name) VALUES ("ricola");
INSERT INTO products (name) VALUES ("milk");
INSERT INTO products (name) VALUES ("onion");
INSERT INTO products (name) VALUES ("ginger");
INSERT INTO products (name) VALUES ("lactose free yogurt");
INSERT INTO products (name) VALUES ("tin tomato");
INSERT INTO products (name) VALUES ("kidney bean");
INSERT INTO products (name) VALUES ("regular pasta");
INSERT INTO products (name) VALUES ("normal pasta");
INSERT INTO products (name) VALUES ("apple");
INSERT INTO products (name) VALUES ("egg");
INSERT INTO products (name) VALUES ("chicken");
INSERT INTO products (name) VALUES ("raisin");
INSERT INTO products (name) VALUES ("seed");
INSERT INTO products (name) VALUES ("yogurt");
INSERT INTO products (name) VALUES ("pasta");
INSERT INTO products (name) VALUES ("honey");
INSERT INTO products (name) VALUES ("lemon");
INSERT INTO products (name) VALUES ("decaf coffee");
INSERT INTO products (name) VALUES ("apple juice");
INSERT INTO products (name) VALUES ("thermometer");
INSERT INTO products (name) VALUES ("beef");
INSERT INTO products (name) VALUES ("edamame");
INSERT INTO products (name) VALUES ("frozen pizza");
INSERT INTO products (name) VALUES ("potato");
INSERT INTO products (name) VALUES ("paracetamol");
INSERT INTO products (name) VALUES ("strepsil");
INSERT INTO products (name) VALUES ("nose spray");
INSERT INTO products (name) VALUES ("hair ties and pin");
INSERT INTO products (name) VALUES ("white wine");
INSERT INTO products (name) VALUES ("detergent");
INSERT INTO products (name) VALUES ("cucumber");
INSERT INTO products (name) VALUES ("gluten free pasta");
INSERT INTO products (name) VALUES ("peanut butter");
INSERT INTO products (name) VALUES ("non dairy yogurt");
INSERT INTO products (name) VALUES ("tonic");
INSERT INTO products (name) VALUES ("almond");
INSERT INTO products (name) VALUES ("vegetable stock cube");
INSERT INTO products (name) VALUES ("rice basmati jazmine");
INSERT INTO products (name) VALUES ("hair conditioner");
INSERT INTO products (name) VALUES ("nutella");
INSERT INTO products (name) VALUES ("sensodyne toothpaste");
INSERT INTO products (name) VALUES ("hotdog");
INSERT INTO products (name) VALUES ("plant pesticide");
INSERT INTO products (name) VALUES ("small pack soil");
INSERT INTO products (name) VALUES ("frozen green bean");
INSERT INTO products (name) VALUES ("tomato");
INSERT INTO products (name) VALUES ("meat");
INSERT INTO products (name) VALUES ("spinach fresh frozen");
INSERT INTO products (name) VALUES ("bell pepper");
INSERT INTO products (name) VALUES ("apples green");
INSERT INTO products (name) VALUES ("test");
INSERT INTO products (name) VALUES ("jdkd");
INSERT INTO products (name) VALUES ("edamame frozen snack");
INSERT INTO products (name) VALUES ("lunch food");
INSERT INTO products (name) VALUES ("vanilla ice cream");
INSERT INTO products (name) VALUES ("avocado");
INSERT INTO products (name) VALUES ("lentil");
INSERT INTO products (name) VALUES ("bacon");
INSERT INTO products (name) VALUES ("cabbage");
INSERT INTO products (name) VALUES ("calabacn");
INSERT INTO products (name) VALUES ("lactose free milk");
INSERT INTO products (name) VALUES ("berenjena");
INSERT INTO products (name) VALUES ("pork loin");
INSERT INTO products (name) VALUES ("fruit");
INSERT INTO products (name) VALUES ("fresh frozen parsley");
INSERT INTO products (name) VALUES ("yoghurt");
INSERT INTO products (name) VALUES ("gluten free pizza cheese");
INSERT INTO products (name) VALUES ("wax strips cera");
INSERT INTO products (name) VALUES ("snack");
INSERT INTO products (name) VALUES ("chocolate peanut");
INSERT INTO products (name) VALUES ("nice dark chocolate");
INSERT INTO products (name) VALUES ("cumin");
INSERT INTO products (name) VALUES ("cheddar");
INSERT INTO products (name) VALUES ("red wine vinegar");
INSERT INTO products (name) VALUES ("canned tomatoes entero frito");
INSERT INTO products (name) VALUES ("gin");
INSERT INTO products (name) VALUES ("semi milk");
INSERT INTO products (name) VALUES ("white wine arteso");
INSERT INTO products (name) VALUES ("jar kidney bean");
INSERT INTO products (name) VALUES ("raspberry");
INSERT INTO products (name) VALUES ("raspberries fruit salat");
INSERT INTO products (name) VALUES ("frozen berry");
INSERT INTO products (name) VALUES ("big garbage bag");
INSERT INTO products (name) VALUES ("black pepper corn");
INSERT INTO products (name) VALUES ("normal decaf coffee");
INSERT INTO products (name) VALUES ("fish");
INSERT INTO products (name) VALUES ("tortilla chip");
INSERT INTO products (name) VALUES ("ground beef");
INSERT INTO products (name) VALUES ("microwave popcorn");
INSERT INTO products (name) VALUES ("sandwhich cheese");
INSERT INTO products (name) VALUES ("ham for toast");
INSERT INTO products (name) VALUES ("gluten free corn flake");
INSERT INTO products (name) VALUES ("toast bread");
INSERT INTO products (name) VALUES ("full fat milk");
INSERT INTO products (name) VALUES ("bread");
INSERT INTO products (name) VALUES ("cream cheese");
INSERT INTO products (name) VALUES ("cherry tomato");
INSERT INTO products (name) VALUES ("hummus");
INSERT INTO products (name) VALUES ("frozen fruit");
INSERT INTO products (name) VALUES ("smoked salmon");
INSERT INTO products (name) VALUES ("sweet potato");
INSERT INTO products (name) VALUES ("white bean");
INSERT INTO products (name) VALUES ("mixed chia seed");
INSERT INTO products (name) VALUES ("youghurt");
INSERT INTO products (name) VALUES ("white rice jasmine basmati");
INSERT INTO products (name) VALUES ("dishwasher tablet");
INSERT INTO products (name) VALUES ("salmon");
INSERT INTO products (name) VALUES ("olive oil");
INSERT INTO products (name) VALUES ("mosquito thing");
INSERT INTO products (name) VALUES ("asperagus");
INSERT INTO products (name) VALUES ("saladwrap kit");
INSERT INTO products (name) VALUES ("brillador");
INSERT INTO products (name) VALUES ("juice");
INSERT INTO products (name) VALUES ("lotion");
INSERT INTO products (name) VALUES ("frozen fish");
INSERT INTO products (name) VALUES ("mayonnaise");
INSERT INTO products (name) VALUES ("frozen bell pepper");
INSERT INTO products (name) VALUES ("feta cheese");
INSERT INTO products (name) VALUES ("risotto rice");
INSERT INTO products (name) VALUES ("mushroom");
INSERT INTO products (name) VALUES ("toilet paper");
INSERT INTO products (name) VALUES ("espresso coffee");
INSERT INTO products (name) VALUES ("chocolate and junk food");
INSERT INTO products (name) VALUES ("frozen shrimp");
INSERT INTO products (name) VALUES ("toothpaste");
INSERT INTO products (name) VALUES ("emergency lesagna");
INSERT INTO products (name) VALUES ("salad");
INSERT INTO products (name) VALUES ("banana");
INSERT INTO products (name) VALUES ("small peeling orange");
INSERT INTO products (name) VALUES ("pasta cheese");
INSERT INTO products (name) VALUES ("berry");
INSERT INTO products (name) VALUES ("wine arteso white");
INSERT INTO products (name) VALUES ("laundry detergent");
INSERT INTO products (name) VALUES ("empanada");
INSERT INTO products (name) VALUES ("fresh tomato");
INSERT INTO products (name) VALUES ("wall nut");
INSERT INTO products (name) VALUES ("brown pasta for salad");
INSERT INTO products (name) VALUES ("tuna");
INSERT INTO products (name) VALUES ("sweet corn");
INSERT INTO products (name) VALUES ("inkonsekvent");
INSERT INTO products (name) VALUES ("suavizante");
INSERT INTO products (name) VALUES ("friegasuelo");
INSERT INTO products (name) VALUES ("lejia");
INSERT INTO products (name) VALUES ("espresso coffee decaf");
INSERT INTO products (name) VALUES ("ice cream");
INSERT INTO products (name) VALUES ("nut");
INSERT INTO products (name) VALUES ("orange");
INSERT INTO products (name) VALUES ("garlic press");
INSERT INTO products (name) VALUES ("shelf");
INSERT INTO products (name) VALUES ("pot");
INSERT INTO products (name) VALUES ("plant");
INSERT INTO products (name) VALUES ("yellow zip bag");
INSERT INTO products (name) VALUES ("metal scrub");
INSERT INTO products (name) VALUES ("dish soap");
INSERT INTO products (name) VALUES ("zip loc bag");
INSERT INTO products (name) VALUES ("kitchen paper");
INSERT INTO products (name) VALUES ("frozen fish empanada huevo");
INSERT INTO products (name) VALUES ("chicken breast");
INSERT INTO products (name) VALUES ("not orange");
INSERT INTO products (name) VALUES ("dill");
INSERT INTO products (name) VALUES ("fresh basil");
INSERT INTO products (name) VALUES ("salt for holiday apt");
INSERT INTO products (name) VALUES ("dijon mustard");
INSERT INTO products (name) VALUES ("feta");
INSERT INTO products (name) VALUES ("vegetable salad");
INSERT INTO products (name) VALUES ("toothpaste for holiday apt guest bath");
INSERT INTO products (name) VALUES ("jam replace holiday appt");
INSERT INTO products (name) VALUES ("tin tomatoes small");
INSERT INTO products (name) VALUES ("long life milk pack");
INSERT INTO products (name) VALUES ("ice");
INSERT INTO products (name) VALUES ("milk fresh");
INSERT INTO products (name) VALUES ("edam cheese");
INSERT INTO products (name) VALUES ("cherry tomat");
INSERT INTO products (name) VALUES ("onions any");
INSERT INTO products (name) VALUES ("vegetables courgette aubergine");
INSERT INTO products (name) VALUES ("breaded frozen fish mercadona");
INSERT INTO products (name) VALUES ("cupboard juice for holiday apt");
INSERT INTO products (name) VALUES ("wine");
INSERT INTO products (name) VALUES ("pork loin carniceria");
INSERT INTO products (name) VALUES ("minced beef");
INSERT INTO products (name) VALUES ("salad cheese supersol");
INSERT INTO products (name) VALUES ("milk supersol");
INSERT INTO products (name) VALUES ("sun dried tomato");
INSERT INTO products (name) VALUES ("picture frame");
INSERT INTO products (name) VALUES ("grater");
INSERT INTO products (name) VALUES ("tahini they have aldi otherwise ignore");
INSERT INTO products (name) VALUES ("greek yogurt");
INSERT INTO products (name) VALUES ("sweetcorn tin");
INSERT INTO products (name) VALUES ("chickpea");
INSERT INTO products (name) VALUES ("nectarines whatever fruit cheapest and works with yogurt");
INSERT INTO products (name) VALUES ("spinach");
INSERT INTO products (name) VALUES ("eggplant");
INSERT INTO products (name) VALUES ("zucchini");
INSERT INTO products (name) VALUES ("bottled water");
INSERT INTO products (name) VALUES ("bay leaves laurel");
INSERT INTO products (name) VALUES ("spegetti");
INSERT INTO products (name) VALUES ("tomato puree");
INSERT INTO products (name) VALUES ("tomatoes tin enteropelado");
INSERT INTO products (name) VALUES ("chili cayendo");
INSERT INTO products (name) VALUES ("rosemary romero");
INSERT INTO products (name) VALUES ("celery");
INSERT INTO products (name) VALUES ("ibuprofen");
INSERT INTO products (name) VALUES ("fenistil");
INSERT INTO products (name) VALUES ("antihistamine");
INSERT INTO products (name) VALUES ("mosquito repellent");
INSERT INTO products (name) VALUES ("bleach");
INSERT INTO products (name) VALUES ("shrimp");
INSERT INTO products (name) VALUES ("cooking butter");
INSERT INTO products (name) VALUES ("fresh parsley");
INSERT INTO products (name) VALUES ("shallot");
INSERT INTO products (name) VALUES ("nice cream");
INSERT INTO products (name) VALUES ("backpack");
INSERT INTO products (name) VALUES ("padel equipment");
INSERT INTO products (name) VALUES ("veg stock cube");
INSERT INTO products (name) VALUES ("paprika spicy sweet");
INSERT INTO products (name) VALUES ("oregano dried");
INSERT INTO products (name) VALUES ("egg pasta pref skinny ribbon shaped like tagliatelle");
INSERT INTO products (name) VALUES ("flour");
INSERT INTO products (name) VALUES ("vinegar");
INSERT INTO products (name) VALUES ("flatbread");
INSERT INTO products (name) VALUES ("cranberry juice");
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week);
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week);
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week);
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week);
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week);
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week);
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week);
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week);
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week);
INSERT INTO weeks (start) SELECT DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "popcorn"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "sliced cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "walnut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "nice black tea carrefour"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "real parmesan"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "sausage"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "carrot"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "ricola"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "onion"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "ginger"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "lactose free yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "tin tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "kidney bean"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "regular pasta"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "normal pasta"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "apple"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "egg"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "chicken"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "raisin"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "seed"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "ginger"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "pasta"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "honey"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "lemon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "onion"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "decaf coffee"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "lemon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "apple juice"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "thermometer"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "chicken"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "beef"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "edamame"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "frozen pizza"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 0 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "popcorn"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "apple"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "potato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "paracetamol"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "strepsil"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "nose spray"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "hair ties and pin"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "white wine"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "detergent"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "gluten free pasta"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "peanut butter"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "non dairy yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "tonic"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "beef"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "almond"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "walnut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "vegetable stock cube"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "rice basmati jazmine"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "hair conditioner"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "nutella"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "sensodyne toothpaste"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "hotdog"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "sausage"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "plant pesticide"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "small pack soil"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "frozen green bean"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "potato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "meat"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "spinach fresh frozen"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "onion"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "bell pepper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "apples green"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "test"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "jdkd"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "edamame frozen snack"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "lunch food"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 1 week)), (SELECT id FROM products WHERE name = "vanilla ice cream"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "avocado"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "lentil"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "bacon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "cabbage"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "avocado"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "calabacn"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "lactose free milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "egg"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "berenjena"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "pork loin"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "fruit"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "bell pepper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "fresh frozen parsley"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "yoghurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "gluten free pizza cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "wax strips cera"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "snack"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "chocolate peanut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "tonic"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "nice dark chocolate"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "cumin"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "cheddar"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "red wine vinegar"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "canned tomatoes entero frito"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "gin"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "semi milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "white wine arteso"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "jar kidney bean"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "apple"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "raspberry"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "raspberries fruit salat"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "frozen berry"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "white wine"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "big garbage bag"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "black pepper corn"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "normal decaf coffee"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "fish"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 2 week)), (SELECT id FROM products WHERE name = "frozen pizza"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "chicken"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "fruit"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "walnut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "tortilla chip"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "ground beef"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "carrot"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "frozen berry"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "microwave popcorn"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "egg"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "sandwhich cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "ham for toast"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "gluten free corn flake"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "almond"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "toast bread"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "full fat milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "bell pepper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "bread"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "cream cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "cherry tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "hummus"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "frozen fruit"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "smoked salmon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "sweet potato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "onion"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "carrot"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "cherry tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "sausage"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "white bean"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "white wine"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "mixed chia seed"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "full fat milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "frozen berry"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "ground beef"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "almond"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 3 week)), (SELECT id FROM products WHERE name = "youghurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "frozen pizza"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "white rice jasmine basmati"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "dishwasher tablet"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "salmon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "olive oil"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "mosquito thing"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "asperagus"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "lemon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "cherry tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "ground beef"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "saladwrap kit"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "brillador"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "juice"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "fruit"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "onion"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "lotion"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "frozen fish"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "mayonnaise"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "bell pepper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "frozen bell pepper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "feta cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "potato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "risotto rice"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "mushroom"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "white wine"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "toilet paper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "espresso coffee"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "chocolate and junk food"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "frozen shrimp"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "toothpaste"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "emergency lesagna"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "tonic"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "salad"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "banana"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "small peeling orange"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 4 week)), (SELECT id FROM products WHERE name = "pork loin"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "ground beef"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "pasta cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "avocado"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "berry"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "wine arteso white"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "laundry detergent"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "egg"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "empanada"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "chicken"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "frozen pizza"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "hummus"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "fruit"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "fresh tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "onion"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "empanada"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "wall nut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "nutella"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "brown pasta for salad"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "egg"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "tuna"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "sweet corn"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "onion"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "fruit"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "inkonsekvent"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "suavizante"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "friegasuelo"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "lejia"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "milk"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "espresso coffee decaf"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "ice cream"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "nut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 5 week)), (SELECT id FROM products WHERE name = "orange"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "garlic press"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "shelf"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "pot"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "plant"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "yellow zip bag"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "kidney bean"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "metal scrub"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "dish soap"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "toilet paper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "fruit"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "smoked salmon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "zip loc bag"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "kitchen paper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "frozen fish empanada huevo"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "chicken breast"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "cream cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "almond"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "walnut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "bread"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "not orange"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "lemon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "dill"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "fresh basil"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "salt for holiday apt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "dijon mustard"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "feta"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "lemon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "bread"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "cream cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "vegetable salad"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "salmon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "toothpaste for holiday apt guest bath"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "dish soap"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "jam replace holiday appt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "ground beef"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "tin tomatoes small"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "pasta"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 6 week)), (SELECT id FROM products WHERE name = "egg"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "pasta cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "smoked salmon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "long life milk pack"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "olive oil"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "ice"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "hummus"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "milk fresh"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "cheddar"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "gin"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "edam cheese"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "cherry tomat"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "onions any"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "carrot"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "cabbage"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "bell pepper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "vegetables courgette aubergine"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "laundry detergent"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "microwave popcorn"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "breaded frozen fish mercadona"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "frozen shrimp"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "cupboard juice for holiday apt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "wine"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "frozen pizza"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "lemon"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "pork loin carniceria"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "walnut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "minced beef"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "chicken"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "espresso coffee"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "cherry tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "pasta"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "mayonnaise"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "salad cheese supersol"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "milk supersol"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "sun dried tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "picture frame"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "grater"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 7 week)), (SELECT id FROM products WHERE name = "egg"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "tahini they have aldi otherwise ignore"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "greek yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "sweetcorn tin"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "chickpea"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "nectarines whatever fruit cheapest and works with yogurt"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "spinach"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "onion"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "cherry tomat"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "bell pepper"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "eggplant"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "zucchini"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "bottled water"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "bay leaves laurel"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "spegetti"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "tomato puree"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "tomatoes tin enteropelado"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "chili cayendo"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "rosemary romero"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "celery"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "ibuprofen"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "fenistil"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "antihistamine"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "mosquito repellent"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "bleach"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "nut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "shrimp"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "cooking butter"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "ground beef"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "fresh parsley"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "fruit"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "shallot"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "potato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "carrot"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "nice cream"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "toothpaste"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "avocado"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "backpack"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "padel equipment"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 8 week)), (SELECT id FROM products WHERE name = "veg stock cube"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "paprika spicy sweet"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "oregano dried"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "egg pasta pref skinny ribbon shaped like tagliatelle"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "flour"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "vinegar"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "olive oil"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "flatbread"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "cabbage"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "mushroom"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "cherry tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "nut"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "bread"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "cherry tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "cucumber"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "cherry tomato"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "cranberry juice"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "egg"), 1);
INSERT INTO items (weekId, productId, userId) VALUES((SELECT id FROM weeks WHERE start = DATE_SUB(CURDATE() - WEEKDAY(CURDATE()), INTERVAL 9 week)), (SELECT id FROM products WHERE name = "potato"), 1);