INSERT INTO products (name) SELECT 'popcorn' WHERE NOT EXISTS (SELECT * FROM products WHERE name='popcorn');
INSERT INTO products (name) SELECT 'sliced cheese' WHERE NOT EXISTS (SELECT * FROM products WHERE name='sliced cheese');
INSERT INTO products (name) SELECT 'walnuts' WHERE NOT EXISTS (SELECT * FROM products WHERE name='walnuts');
INSERT INTO products (name) SELECT 'nice black tea carrefour' WHERE NOT EXISTS (SELECT * FROM products WHERE name='nice black tea carrefour');
INSERT INTO products (name) SELECT 'real parmesan' WHERE NOT EXISTS (SELECT * FROM products WHERE name='real parmesan');
INSERT INTO products (name) SELECT 'sausages' WHERE NOT EXISTS (SELECT * FROM products WHERE name='sausages');
INSERT INTO products (name) SELECT 'carrots' WHERE NOT EXISTS (SELECT * FROM products WHERE name='carrots');
INSERT INTO products (name) SELECT 'ricola' WHERE NOT EXISTS (SELECT * FROM products WHERE name='ricola');
INSERT INTO products (name) SELECT 'milk' WHERE NOT EXISTS (SELECT * FROM products WHERE name='milk');
INSERT INTO products (name) SELECT 'onions' WHERE NOT EXISTS (SELECT * FROM products WHERE name='onions');
INSERT INTO products (name) SELECT 'ginger' WHERE NOT EXISTS (SELECT * FROM products WHERE name='ginger');
INSERT INTO products (name) SELECT 'lactose free yogurt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='lactose free yogurt');
INSERT INTO products (name) SELECT 'tin tomatoes' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tin tomatoes');
INSERT INTO products (name) SELECT 'kidney beans' WHERE NOT EXISTS (SELECT * FROM products WHERE name='kidney beans');
INSERT INTO products (name) SELECT 'regular pasta' WHERE NOT EXISTS (SELECT * FROM products WHERE name='regular pasta');
INSERT INTO products (name) SELECT 'normal pasta' WHERE NOT EXISTS (SELECT * FROM products WHERE name='normal pasta');
INSERT INTO products (name) SELECT 'apples' WHERE NOT EXISTS (SELECT * FROM products WHERE name='apples');
INSERT INTO products (name) SELECT 'eggs' WHERE NOT EXISTS (SELECT * FROM products WHERE name='eggs');
INSERT INTO products (name) SELECT 'chicken' WHERE NOT EXISTS (SELECT * FROM products WHERE name='chicken');
INSERT INTO products (name) SELECT 'raisins' WHERE NOT EXISTS (SELECT * FROM products WHERE name='raisins');
INSERT INTO products (name) SELECT 'seeds' WHERE NOT EXISTS (SELECT * FROM products WHERE name='seeds');
INSERT INTO products (name) SELECT 'yogurt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='yogurt');
INSERT INTO products (name) SELECT 'pasta' WHERE NOT EXISTS (SELECT * FROM products WHERE name='pasta');
INSERT INTO products (name) SELECT 'honey' WHERE NOT EXISTS (SELECT * FROM products WHERE name='honey');
INSERT INTO products (name) SELECT 'lemons' WHERE NOT EXISTS (SELECT * FROM products WHERE name='lemons');
INSERT INTO products (name) SELECT 'decaf coffee' WHERE NOT EXISTS (SELECT * FROM products WHERE name='decaf coffee');
INSERT INTO products (name) SELECT 'lemon' WHERE NOT EXISTS (SELECT * FROM products WHERE name='lemon');
INSERT INTO products (name) SELECT 'apple juice' WHERE NOT EXISTS (SELECT * FROM products WHERE name='apple juice');
INSERT INTO products (name) SELECT 'thermometer' WHERE NOT EXISTS (SELECT * FROM products WHERE name='thermometer');
INSERT INTO products (name) SELECT 'beef' WHERE NOT EXISTS (SELECT * FROM products WHERE name='beef');
INSERT INTO products (name) SELECT 'edamame' WHERE NOT EXISTS (SELECT * FROM products WHERE name='edamame');
INSERT INTO products (name) SELECT 'frozen pizzas' WHERE NOT EXISTS (SELECT * FROM products WHERE name='frozen pizzas');
INSERT INTO products (name) SELECT 'potatoes' WHERE NOT EXISTS (SELECT * FROM products WHERE name='potatoes');
INSERT INTO products (name) SELECT 'paracetamol' WHERE NOT EXISTS (SELECT * FROM products WHERE name='paracetamol');
INSERT INTO products (name) SELECT 'strepsil' WHERE NOT EXISTS (SELECT * FROM products WHERE name='strepsil');
INSERT INTO products (name) SELECT 'nose spray' WHERE NOT EXISTS (SELECT * FROM products WHERE name='nose spray');
INSERT INTO products (name) SELECT 'hair ties and pins' WHERE NOT EXISTS (SELECT * FROM products WHERE name='hair ties and pins');
INSERT INTO products (name) SELECT 'white wine' WHERE NOT EXISTS (SELECT * FROM products WHERE name='white wine');
INSERT INTO products (name) SELECT 'detergent' WHERE NOT EXISTS (SELECT * FROM products WHERE name='detergent');
INSERT INTO products (name) SELECT 'cucumber' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cucumber');
INSERT INTO products (name) SELECT 'gluten free pasta' WHERE NOT EXISTS (SELECT * FROM products WHERE name='gluten free pasta');
INSERT INTO products (name) SELECT 'peanut butter' WHERE NOT EXISTS (SELECT * FROM products WHERE name='peanut butter');
INSERT INTO products (name) SELECT 'non dairy yogurt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='non dairy yogurt');
INSERT INTO products (name) SELECT 'tonic' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tonic');
INSERT INTO products (name) SELECT 'almonds' WHERE NOT EXISTS (SELECT * FROM products WHERE name='almonds');
INSERT INTO products (name) SELECT 'walnut' WHERE NOT EXISTS (SELECT * FROM products WHERE name='walnut');
INSERT INTO products (name) SELECT 'vegetable stock cubes' WHERE NOT EXISTS (SELECT * FROM products WHERE name='vegetable stock cubes');
INSERT INTO products (name) SELECT 'rice basmati jazmine' WHERE NOT EXISTS (SELECT * FROM products WHERE name='rice basmati jazmine');
INSERT INTO products (name) SELECT 'hair conditioner' WHERE NOT EXISTS (SELECT * FROM products WHERE name='hair conditioner');
INSERT INTO products (name) SELECT 'nutella' WHERE NOT EXISTS (SELECT * FROM products WHERE name='nutella');
INSERT INTO products (name) SELECT 'sensodyne toothpaste' WHERE NOT EXISTS (SELECT * FROM products WHERE name='sensodyne toothpaste');
INSERT INTO products (name) SELECT 'hotdogs' WHERE NOT EXISTS (SELECT * FROM products WHERE name='hotdogs');
INSERT INTO products (name) SELECT 'plant pesticides' WHERE NOT EXISTS (SELECT * FROM products WHERE name='plant pesticides');
INSERT INTO products (name) SELECT 'small pack soil' WHERE NOT EXISTS (SELECT * FROM products WHERE name='small pack soil');
INSERT INTO products (name) SELECT 'frozen green beans' WHERE NOT EXISTS (SELECT * FROM products WHERE name='frozen green beans');
INSERT INTO products (name) SELECT 'tomatoes' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tomatoes');
INSERT INTO products (name) SELECT 'meat' WHERE NOT EXISTS (SELECT * FROM products WHERE name='meat');
INSERT INTO products (name) SELECT 'spinach fresh frozen' WHERE NOT EXISTS (SELECT * FROM products WHERE name='spinach fresh frozen');
INSERT INTO products (name) SELECT 'onion' WHERE NOT EXISTS (SELECT * FROM products WHERE name='onion');
INSERT INTO products (name) SELECT 'bell peppers' WHERE NOT EXISTS (SELECT * FROM products WHERE name='bell peppers');
INSERT INTO products (name) SELECT 'apples green' WHERE NOT EXISTS (SELECT * FROM products WHERE name='apples green');
INSERT INTO products (name) SELECT 'test' WHERE NOT EXISTS (SELECT * FROM products WHERE name='test');
INSERT INTO products (name) SELECT 'jdkd' WHERE NOT EXISTS (SELECT * FROM products WHERE name='jdkd');
INSERT INTO products (name) SELECT 'edamame frozen snack' WHERE NOT EXISTS (SELECT * FROM products WHERE name='edamame frozen snack');
INSERT INTO products (name) SELECT 'lunch food' WHERE NOT EXISTS (SELECT * FROM products WHERE name='lunch food');
INSERT INTO products (name) SELECT 'vanilla ice cream' WHERE NOT EXISTS (SELECT * FROM products WHERE name='vanilla ice cream');
INSERT INTO products (name) SELECT 'avocados' WHERE NOT EXISTS (SELECT * FROM products WHERE name='avocados');
INSERT INTO products (name) SELECT 'lentils' WHERE NOT EXISTS (SELECT * FROM products WHERE name='lentils');
INSERT INTO products (name) SELECT 'bacon' WHERE NOT EXISTS (SELECT * FROM products WHERE name='bacon');
INSERT INTO products (name) SELECT 'cabbage' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cabbage');
INSERT INTO products (name) SELECT 'avocado' WHERE NOT EXISTS (SELECT * FROM products WHERE name='avocado');
INSERT INTO products (name) SELECT 'calabacn' WHERE NOT EXISTS (SELECT * FROM products WHERE name='calabacn');
INSERT INTO products (name) SELECT 'lactose free milk' WHERE NOT EXISTS (SELECT * FROM products WHERE name='lactose free milk');
INSERT INTO products (name) SELECT 'berenjena' WHERE NOT EXISTS (SELECT * FROM products WHERE name='berenjena');
INSERT INTO products (name) SELECT 'pork loin' WHERE NOT EXISTS (SELECT * FROM products WHERE name='pork loin');
INSERT INTO products (name) SELECT 'fruit' WHERE NOT EXISTS (SELECT * FROM products WHERE name='fruit');
INSERT INTO products (name) SELECT 'bell pepper' WHERE NOT EXISTS (SELECT * FROM products WHERE name='bell pepper');
INSERT INTO products (name) SELECT 'fresh frozen parsley' WHERE NOT EXISTS (SELECT * FROM products WHERE name='fresh frozen parsley');
INSERT INTO products (name) SELECT 'yoghurt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='yoghurt');
INSERT INTO products (name) SELECT 'gluten free pizza cheese' WHERE NOT EXISTS (SELECT * FROM products WHERE name='gluten free pizza cheese');
INSERT INTO products (name) SELECT 'wax strips cera' WHERE NOT EXISTS (SELECT * FROM products WHERE name='wax strips cera');
INSERT INTO products (name) SELECT 'snacks' WHERE NOT EXISTS (SELECT * FROM products WHERE name='snacks');
INSERT INTO products (name) SELECT 'chocolate peanuts' WHERE NOT EXISTS (SELECT * FROM products WHERE name='chocolate peanuts');
INSERT INTO products (name) SELECT 'nice dark chocolate' WHERE NOT EXISTS (SELECT * FROM products WHERE name='nice dark chocolate');
INSERT INTO products (name) SELECT 'cumin' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cumin');
INSERT INTO products (name) SELECT 'cheddar' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cheddar');
INSERT INTO products (name) SELECT 'red wine vinegar' WHERE NOT EXISTS (SELECT * FROM products WHERE name='red wine vinegar');
INSERT INTO products (name) SELECT 'canned tomatoes entero frito' WHERE NOT EXISTS (SELECT * FROM products WHERE name='canned tomatoes entero frito');
INSERT INTO products (name) SELECT 'gin' WHERE NOT EXISTS (SELECT * FROM products WHERE name='gin');
INSERT INTO products (name) SELECT 'semi milk' WHERE NOT EXISTS (SELECT * FROM products WHERE name='semi milk');
INSERT INTO products (name) SELECT 'white wine arteso' WHERE NOT EXISTS (SELECT * FROM products WHERE name='white wine arteso');
INSERT INTO products (name) SELECT 'jar kidney beans' WHERE NOT EXISTS (SELECT * FROM products WHERE name='jar kidney beans');
INSERT INTO products (name) SELECT 'raspberry' WHERE NOT EXISTS (SELECT * FROM products WHERE name='raspberry');
INSERT INTO products (name) SELECT 'raspberries fruit salat' WHERE NOT EXISTS (SELECT * FROM products WHERE name='raspberries fruit salat');
INSERT INTO products (name) SELECT 'frozen berries' WHERE NOT EXISTS (SELECT * FROM products WHERE name='frozen berries');
INSERT INTO products (name) SELECT 'big garbage bags' WHERE NOT EXISTS (SELECT * FROM products WHERE name='big garbage bags');
INSERT INTO products (name) SELECT 'black pepper corns' WHERE NOT EXISTS (SELECT * FROM products WHERE name='black pepper corns');
INSERT INTO products (name) SELECT 'normal decaf coffee' WHERE NOT EXISTS (SELECT * FROM products WHERE name='normal decaf coffee');
INSERT INTO products (name) SELECT 'fish' WHERE NOT EXISTS (SELECT * FROM products WHERE name='fish');
INSERT INTO products (name) SELECT 'frozen pizza' WHERE NOT EXISTS (SELECT * FROM products WHERE name='frozen pizza');
INSERT INTO products (name) SELECT 'tortilla chips' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tortilla chips');
INSERT INTO products (name) SELECT 'ground beef' WHERE NOT EXISTS (SELECT * FROM products WHERE name='ground beef');
INSERT INTO products (name) SELECT 'microwave popcorn' WHERE NOT EXISTS (SELECT * FROM products WHERE name='microwave popcorn');
INSERT INTO products (name) SELECT 'sandwhich cheese' WHERE NOT EXISTS (SELECT * FROM products WHERE name='sandwhich cheese');
INSERT INTO products (name) SELECT 'ham for toast' WHERE NOT EXISTS (SELECT * FROM products WHERE name='ham for toast');
INSERT INTO products (name) SELECT 'gluten free corn flakes' WHERE NOT EXISTS (SELECT * FROM products WHERE name='gluten free corn flakes');
INSERT INTO products (name) SELECT 'toast bread' WHERE NOT EXISTS (SELECT * FROM products WHERE name='toast bread');
INSERT INTO products (name) SELECT 'full fat milk' WHERE NOT EXISTS (SELECT * FROM products WHERE name='full fat milk');
INSERT INTO products (name) SELECT 'bread' WHERE NOT EXISTS (SELECT * FROM products WHERE name='bread');
INSERT INTO products (name) SELECT 'cream cheese' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cream cheese');
INSERT INTO products (name) SELECT 'cherry tomatoes' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cherry tomatoes');
INSERT INTO products (name) SELECT 'hummus' WHERE NOT EXISTS (SELECT * FROM products WHERE name='hummus');
INSERT INTO products (name) SELECT 'frozen fruit' WHERE NOT EXISTS (SELECT * FROM products WHERE name='frozen fruit');
INSERT INTO products (name) SELECT 'smoked salmon' WHERE NOT EXISTS (SELECT * FROM products WHERE name='smoked salmon');
INSERT INTO products (name) SELECT 'sweet potato' WHERE NOT EXISTS (SELECT * FROM products WHERE name='sweet potato');
INSERT INTO products (name) SELECT 'sausage' WHERE NOT EXISTS (SELECT * FROM products WHERE name='sausage');
INSERT INTO products (name) SELECT 'white beans' WHERE NOT EXISTS (SELECT * FROM products WHERE name='white beans');
INSERT INTO products (name) SELECT 'mixed chia seeds' WHERE NOT EXISTS (SELECT * FROM products WHERE name='mixed chia seeds');
INSERT INTO products (name) SELECT 'youghurt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='youghurt');
INSERT INTO products (name) SELECT 'white rice jasmine basmati' WHERE NOT EXISTS (SELECT * FROM products WHERE name='white rice jasmine basmati');
INSERT INTO products (name) SELECT 'dishwasher tablets' WHERE NOT EXISTS (SELECT * FROM products WHERE name='dishwasher tablets');
INSERT INTO products (name) SELECT 'salmon' WHERE NOT EXISTS (SELECT * FROM products WHERE name='salmon');
INSERT INTO products (name) SELECT 'olive oil' WHERE NOT EXISTS (SELECT * FROM products WHERE name='olive oil');
INSERT INTO products (name) SELECT 'mosquito thing' WHERE NOT EXISTS (SELECT * FROM products WHERE name='mosquito thing');
INSERT INTO products (name) SELECT 'asperagus' WHERE NOT EXISTS (SELECT * FROM products WHERE name='asperagus');
INSERT INTO products (name) SELECT 'cucumbers' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cucumbers');
INSERT INTO products (name) SELECT 'saladwrap kit' WHERE NOT EXISTS (SELECT * FROM products WHERE name='saladwrap kit');
INSERT INTO products (name) SELECT 'brillador' WHERE NOT EXISTS (SELECT * FROM products WHERE name='brillador');
INSERT INTO products (name) SELECT 'juice' WHERE NOT EXISTS (SELECT * FROM products WHERE name='juice');
INSERT INTO products (name) SELECT 'lotion' WHERE NOT EXISTS (SELECT * FROM products WHERE name='lotion');
INSERT INTO products (name) SELECT 'frozen fish' WHERE NOT EXISTS (SELECT * FROM products WHERE name='frozen fish');
INSERT INTO products (name) SELECT 'mayonnaise' WHERE NOT EXISTS (SELECT * FROM products WHERE name='mayonnaise');
INSERT INTO products (name) SELECT 'frozen bell pepper' WHERE NOT EXISTS (SELECT * FROM products WHERE name='frozen bell pepper');
INSERT INTO products (name) SELECT 'feta cheese' WHERE NOT EXISTS (SELECT * FROM products WHERE name='feta cheese');
INSERT INTO products (name) SELECT 'risotto rice' WHERE NOT EXISTS (SELECT * FROM products WHERE name='risotto rice');
INSERT INTO products (name) SELECT 'mushrooms' WHERE NOT EXISTS (SELECT * FROM products WHERE name='mushrooms');
INSERT INTO products (name) SELECT 'toilet paper' WHERE NOT EXISTS (SELECT * FROM products WHERE name='toilet paper');
INSERT INTO products (name) SELECT 'espresso coffee' WHERE NOT EXISTS (SELECT * FROM products WHERE name='espresso coffee');
INSERT INTO products (name) SELECT 'chocolate and junk food' WHERE NOT EXISTS (SELECT * FROM products WHERE name='chocolate and junk food');
INSERT INTO products (name) SELECT 'frozen shrimp' WHERE NOT EXISTS (SELECT * FROM products WHERE name='frozen shrimp');
INSERT INTO products (name) SELECT 'toothpaste' WHERE NOT EXISTS (SELECT * FROM products WHERE name='toothpaste');
INSERT INTO products (name) SELECT 'emergency lesagna' WHERE NOT EXISTS (SELECT * FROM products WHERE name='emergency lesagna');
INSERT INTO products (name) SELECT 'salad' WHERE NOT EXISTS (SELECT * FROM products WHERE name='salad');
INSERT INTO products (name) SELECT 'bananas' WHERE NOT EXISTS (SELECT * FROM products WHERE name='bananas');
INSERT INTO products (name) SELECT 'small peeling oranges' WHERE NOT EXISTS (SELECT * FROM products WHERE name='small peeling oranges');
INSERT INTO products (name) SELECT 'pasta cheese' WHERE NOT EXISTS (SELECT * FROM products WHERE name='pasta cheese');
INSERT INTO products (name) SELECT 'berries' WHERE NOT EXISTS (SELECT * FROM products WHERE name='berries');
INSERT INTO products (name) SELECT 'wine arteso white' WHERE NOT EXISTS (SELECT * FROM products WHERE name='wine arteso white');
INSERT INTO products (name) SELECT 'laundry detergent' WHERE NOT EXISTS (SELECT * FROM products WHERE name='laundry detergent');
INSERT INTO products (name) SELECT 'empanada' WHERE NOT EXISTS (SELECT * FROM products WHERE name='empanada');
INSERT INTO products (name) SELECT 'fresh tomatoes' WHERE NOT EXISTS (SELECT * FROM products WHERE name='fresh tomatoes');
INSERT INTO products (name) SELECT 'wall nuts' WHERE NOT EXISTS (SELECT * FROM products WHERE name='wall nuts');
INSERT INTO products (name) SELECT 'brown pasta for salad' WHERE NOT EXISTS (SELECT * FROM products WHERE name='brown pasta for salad');
INSERT INTO products (name) SELECT 'tuna' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tuna');
INSERT INTO products (name) SELECT 'sweet corn' WHERE NOT EXISTS (SELECT * FROM products WHERE name='sweet corn');
INSERT INTO products (name) SELECT 'fruits' WHERE NOT EXISTS (SELECT * FROM products WHERE name='fruits');
INSERT INTO products (name) SELECT 'tomato' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tomato');
INSERT INTO products (name) SELECT 'inkonsekvent' WHERE NOT EXISTS (SELECT * FROM products WHERE name='inkonsekvent');
INSERT INTO products (name) SELECT 'suavizante' WHERE NOT EXISTS (SELECT * FROM products WHERE name='suavizante');
INSERT INTO products (name) SELECT 'friegasuelos' WHERE NOT EXISTS (SELECT * FROM products WHERE name='friegasuelos');
INSERT INTO products (name) SELECT 'lejia' WHERE NOT EXISTS (SELECT * FROM products WHERE name='lejia');
INSERT INTO products (name) SELECT 'espresso coffee decaf' WHERE NOT EXISTS (SELECT * FROM products WHERE name='espresso coffee decaf');
INSERT INTO products (name) SELECT 'ice cream' WHERE NOT EXISTS (SELECT * FROM products WHERE name='ice cream');
INSERT INTO products (name) SELECT 'nuts' WHERE NOT EXISTS (SELECT * FROM products WHERE name='nuts');
INSERT INTO products (name) SELECT 'oranges' WHERE NOT EXISTS (SELECT * FROM products WHERE name='oranges');
INSERT INTO products (name) SELECT 'garlic press' WHERE NOT EXISTS (SELECT * FROM products WHERE name='garlic press');
INSERT INTO products (name) SELECT 'shelves' WHERE NOT EXISTS (SELECT * FROM products WHERE name='shelves');
INSERT INTO products (name) SELECT 'pots' WHERE NOT EXISTS (SELECT * FROM products WHERE name='pots');
INSERT INTO products (name) SELECT 'plants' WHERE NOT EXISTS (SELECT * FROM products WHERE name='plants');
INSERT INTO products (name) SELECT 'yellow zip bags' WHERE NOT EXISTS (SELECT * FROM products WHERE name='yellow zip bags');
INSERT INTO products (name) SELECT 'metal scrub' WHERE NOT EXISTS (SELECT * FROM products WHERE name='metal scrub');
INSERT INTO products (name) SELECT 'dish soap' WHERE NOT EXISTS (SELECT * FROM products WHERE name='dish soap');
INSERT INTO products (name) SELECT 'zip loc bags' WHERE NOT EXISTS (SELECT * FROM products WHERE name='zip loc bags');
INSERT INTO products (name) SELECT 'kitchen paper' WHERE NOT EXISTS (SELECT * FROM products WHERE name='kitchen paper');
INSERT INTO products (name) SELECT 'frozen fish empanada huevo' WHERE NOT EXISTS (SELECT * FROM products WHERE name='frozen fish empanada huevo');
INSERT INTO products (name) SELECT 'chicken breast' WHERE NOT EXISTS (SELECT * FROM products WHERE name='chicken breast');
INSERT INTO products (name) SELECT 'not oranges' WHERE NOT EXISTS (SELECT * FROM products WHERE name='not oranges');
INSERT INTO products (name) SELECT 'dill' WHERE NOT EXISTS (SELECT * FROM products WHERE name='dill');
INSERT INTO products (name) SELECT 'fresh basil' WHERE NOT EXISTS (SELECT * FROM products WHERE name='fresh basil');
INSERT INTO products (name) SELECT 'salt for holiday apt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='salt for holiday apt');
INSERT INTO products (name) SELECT 'dijon mustard' WHERE NOT EXISTS (SELECT * FROM products WHERE name='dijon mustard');
INSERT INTO products (name) SELECT 'feta' WHERE NOT EXISTS (SELECT * FROM products WHERE name='feta');
INSERT INTO products (name) SELECT 'vegetable salad' WHERE NOT EXISTS (SELECT * FROM products WHERE name='vegetable salad');
INSERT INTO products (name) SELECT 'toothpaste for holiday apt guest bath' WHERE NOT EXISTS (SELECT * FROM products WHERE name='toothpaste for holiday apt guest bath');
INSERT INTO products (name) SELECT 'jam replace holiday appt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='jam replace holiday appt');
INSERT INTO products (name) SELECT 'tin tomatoes small' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tin tomatoes small');
INSERT INTO products (name) SELECT 'long life milk pack' WHERE NOT EXISTS (SELECT * FROM products WHERE name='long life milk pack');
INSERT INTO products (name) SELECT 'ice' WHERE NOT EXISTS (SELECT * FROM products WHERE name='ice');
INSERT INTO products (name) SELECT 'milk fresh' WHERE NOT EXISTS (SELECT * FROM products WHERE name='milk fresh');
INSERT INTO products (name) SELECT 'edam cheese' WHERE NOT EXISTS (SELECT * FROM products WHERE name='edam cheese');
INSERT INTO products (name) SELECT 'cherry tomat' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cherry tomat');
INSERT INTO products (name) SELECT 'onions any' WHERE NOT EXISTS (SELECT * FROM products WHERE name='onions any');
INSERT INTO products (name) SELECT 'vegetables courgette aubergine' WHERE NOT EXISTS (SELECT * FROM products WHERE name='vegetables courgette aubergine');
INSERT INTO products (name) SELECT 'breaded frozen fish mercadona' WHERE NOT EXISTS (SELECT * FROM products WHERE name='breaded frozen fish mercadona');
INSERT INTO products (name) SELECT 'cupboard juice for holiday apt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cupboard juice for holiday apt');
INSERT INTO products (name) SELECT 'wine' WHERE NOT EXISTS (SELECT * FROM products WHERE name='wine');
INSERT INTO products (name) SELECT 'pork loin carniceria' WHERE NOT EXISTS (SELECT * FROM products WHERE name='pork loin carniceria');
INSERT INTO products (name) SELECT 'minced beef' WHERE NOT EXISTS (SELECT * FROM products WHERE name='minced beef');
INSERT INTO products (name) SELECT 'salad cheese supersol' WHERE NOT EXISTS (SELECT * FROM products WHERE name='salad cheese supersol');
INSERT INTO products (name) SELECT 'milk supersol' WHERE NOT EXISTS (SELECT * FROM products WHERE name='milk supersol');
INSERT INTO products (name) SELECT 'sun dried tomatoes' WHERE NOT EXISTS (SELECT * FROM products WHERE name='sun dried tomatoes');
INSERT INTO products (name) SELECT 'picture frame' WHERE NOT EXISTS (SELECT * FROM products WHERE name='picture frame');
INSERT INTO products (name) SELECT 'grater' WHERE NOT EXISTS (SELECT * FROM products WHERE name='grater');
INSERT INTO products (name) SELECT 'tahini they have aldi otherwise ignore' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tahini they have aldi otherwise ignore');
INSERT INTO products (name) SELECT 'greek yogurt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='greek yogurt');
INSERT INTO products (name) SELECT 'sweetcorn tin' WHERE NOT EXISTS (SELECT * FROM products WHERE name='sweetcorn tin');
INSERT INTO products (name) SELECT 'chickpeas' WHERE NOT EXISTS (SELECT * FROM products WHERE name='chickpeas');
INSERT INTO products (name) SELECT 'nectarines whatever fruit cheapest and works with yogurt' WHERE NOT EXISTS (SELECT * FROM products WHERE name='nectarines whatever fruit cheapest and works with yogurt');
INSERT INTO products (name) SELECT 'spinach' WHERE NOT EXISTS (SELECT * FROM products WHERE name='spinach');
INSERT INTO products (name) SELECT 'eggplant' WHERE NOT EXISTS (SELECT * FROM products WHERE name='eggplant');
INSERT INTO products (name) SELECT 'zucchini' WHERE NOT EXISTS (SELECT * FROM products WHERE name='zucchini');
INSERT INTO products (name) SELECT 'bottled water' WHERE NOT EXISTS (SELECT * FROM products WHERE name='bottled water');
INSERT INTO products (name) SELECT 'bay leaves laurels' WHERE NOT EXISTS (SELECT * FROM products WHERE name='bay leaves laurels');
INSERT INTO products (name) SELECT 'spegetti' WHERE NOT EXISTS (SELECT * FROM products WHERE name='spegetti');
INSERT INTO products (name) SELECT 'tomato puree' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tomato puree');
INSERT INTO products (name) SELECT 'tomatoes tin enteropelado' WHERE NOT EXISTS (SELECT * FROM products WHERE name='tomatoes tin enteropelado');
INSERT INTO products (name) SELECT 'chili cayendo' WHERE NOT EXISTS (SELECT * FROM products WHERE name='chili cayendo');
INSERT INTO products (name) SELECT 'rosemary romero' WHERE NOT EXISTS (SELECT * FROM products WHERE name='rosemary romero');
INSERT INTO products (name) SELECT 'celery' WHERE NOT EXISTS (SELECT * FROM products WHERE name='celery');
INSERT INTO products (name) SELECT 'ibuprofen' WHERE NOT EXISTS (SELECT * FROM products WHERE name='ibuprofen');
INSERT INTO products (name) SELECT 'fenistil' WHERE NOT EXISTS (SELECT * FROM products WHERE name='fenistil');
INSERT INTO products (name) SELECT 'antihistamine' WHERE NOT EXISTS (SELECT * FROM products WHERE name='antihistamine');
INSERT INTO products (name) SELECT 'mosquito repellent' WHERE NOT EXISTS (SELECT * FROM products WHERE name='mosquito repellent');
INSERT INTO products (name) SELECT 'bleach' WHERE NOT EXISTS (SELECT * FROM products WHERE name='bleach');
INSERT INTO products (name) SELECT 'shrimp' WHERE NOT EXISTS (SELECT * FROM products WHERE name='shrimp');
INSERT INTO products (name) SELECT 'cooking butter' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cooking butter');
INSERT INTO products (name) SELECT 'fresh parsley' WHERE NOT EXISTS (SELECT * FROM products WHERE name='fresh parsley');
INSERT INTO products (name) SELECT 'shallots' WHERE NOT EXISTS (SELECT * FROM products WHERE name='shallots');
INSERT INTO products (name) SELECT 'nice cream' WHERE NOT EXISTS (SELECT * FROM products WHERE name='nice cream');
INSERT INTO products (name) SELECT 'backpacks' WHERE NOT EXISTS (SELECT * FROM products WHERE name='backpacks');
INSERT INTO products (name) SELECT 'padel equipment' WHERE NOT EXISTS (SELECT * FROM products WHERE name='padel equipment');
INSERT INTO products (name) SELECT 'veg stock cubes' WHERE NOT EXISTS (SELECT * FROM products WHERE name='veg stock cubes');
INSERT INTO products (name) SELECT 'paprika spicy sweet' WHERE NOT EXISTS (SELECT * FROM products WHERE name='paprika spicy sweet');
INSERT INTO products (name) SELECT 'oregano dried' WHERE NOT EXISTS (SELECT * FROM products WHERE name='oregano dried');
INSERT INTO products (name) SELECT 'egg pasta pref skinny ribbon shaped like tagliatelle' WHERE NOT EXISTS (SELECT * FROM products WHERE name='egg pasta pref skinny ribbon shaped like tagliatelle');
INSERT INTO products (name) SELECT 'flour' WHERE NOT EXISTS (SELECT * FROM products WHERE name='flour');
INSERT INTO products (name) SELECT 'vinegar' WHERE NOT EXISTS (SELECT * FROM products WHERE name='vinegar');
INSERT INTO products (name) SELECT 'flatbread' WHERE NOT EXISTS (SELECT * FROM products WHERE name='flatbread');
INSERT INTO products (name) SELECT 'cranberry juice' WHERE NOT EXISTS (SELECT * FROM products WHERE name='cranberry juice');
INSERT INTO products (name) SELECT 'potato' WHERE NOT EXISTS (SELECT * FROM products WHERE name='potato');
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 0 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 0 week));
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 1 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 1 week));
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 2 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 2 week));
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 3 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 3 week));
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 4 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 4 week));
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 5 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 5 week));
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 6 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 6 week));
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 7 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 7 week));
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 8 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 8 week));
INSERT INTO weeks (start) SELECT DATE_SUB('2020-10-12',INTERVAL 9 week) WHERE NOT EXISTS (SELECT * FROM weeks WHERE start= DATE_SUB('2020-10-12',INTERVAL 9 week));
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='popcorn';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='sliced cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='walnuts';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='nice black tea carrefour';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='real parmesan';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='sausages';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='carrots';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='ricola';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='onions';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='ginger';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='lactose free yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='tin tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='kidney beans';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='regular pasta';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='normal pasta';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='apples';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='eggs';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='chicken';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='raisins';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='seeds';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='ginger';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='pasta';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='honey';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='lemons';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='onions';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='decaf coffee';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='lemon';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='apple juice';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='thermometer';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='chicken';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='beef';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='edamame';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='frozen pizzas';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 0 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='popcorn';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='apples';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='potatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='paracetamol';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='strepsil';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='nose spray';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='hair ties and pins';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='white wine';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='detergent';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='cucumber';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='gluten free pasta';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='peanut butter';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='non dairy yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='tonic';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='beef';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='almonds';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='walnut';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='vegetable stock cubes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='rice basmati jazmine';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='hair conditioner';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='nutella';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='sensodyne toothpaste';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='hotdogs';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='sausages';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='plant pesticides';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='small pack soil';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='frozen green beans';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='potatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='meat';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='spinach fresh frozen';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='onion';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='bell peppers';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='apples green';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='test';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='jdkd';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='edamame frozen snack';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='lunch food';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 1 week) AND name='vanilla ice cream';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='avocados';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='lentils';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='bacon';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='cabbage';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='avocado';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='calabacn';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='lactose free milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='eggs';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='berenjena';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='pork loin';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='fruit';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='bell pepper';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='fresh frozen parsley';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='yoghurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='gluten free pizza cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='wax strips cera';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='snacks';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='chocolate peanuts';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='tonic';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='nice dark chocolate';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='cumin';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='cheddar';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='red wine vinegar';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='canned tomatoes entero frito';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='gin';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='semi milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='white wine arteso';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='jar kidney beans';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='apples';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='raspberry';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='raspberries fruit salat';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='frozen berries';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='white wine';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='big garbage bags';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='black pepper corns';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='normal decaf coffee';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='fish';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 2 week) AND name='frozen pizza';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='chicken';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='fruit';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='walnuts';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='tortilla chips';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='ground beef';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='carrots';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='cucumber';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='frozen berries';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='microwave popcorn';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='eggs';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='sandwhich cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='ham for toast';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='gluten free corn flakes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='almonds';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='toast bread';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='full fat milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='bell peppers';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='bread';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='cream cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='cherry tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='hummus';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='frozen fruit';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='smoked salmon';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='sweet potato';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='onion';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='carrots';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='cucumber';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='cherry tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='sausage';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='white beans';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='white wine';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='mixed chia seeds';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='full fat milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='frozen berries';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='ground beef';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='almonds';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 3 week) AND name='youghurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='frozen pizza';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='white rice jasmine basmati';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='dishwasher tablets';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='salmon';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='olive oil';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='mosquito thing';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='asperagus';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='lemons';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='cherry tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='cucumbers';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='ground beef';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='saladwrap kit';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='brillador';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='juice';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='fruit';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='onion';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='lotion';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='frozen fish';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='mayonnaise';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='bell pepper';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='frozen bell pepper';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='feta cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='potatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='risotto rice';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='mushrooms';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='white wine';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='toilet paper';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='espresso coffee';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='cucumber';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='chocolate and junk food';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='frozen shrimp';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='toothpaste';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='emergency lesagna';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='tonic';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='salad';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='bananas';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='small peeling oranges';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 4 week) AND name='pork loin';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='ground beef';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='pasta cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='avocado';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='berries';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='wine arteso white';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='laundry detergent';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='eggs';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='empanada';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='chicken';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='frozen pizza';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='hummus';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='fruit';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='fresh tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='cucumber';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='onion';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='empanada';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='wall nuts';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='nutella';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='brown pasta for salad';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='eggs';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='tuna';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='sweet corn';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='onions';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='fruits';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='cucumber';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='tomato';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='inkonsekvent';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='suavizante';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='friegasuelos';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='lejia';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='milk';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='espresso coffee decaf';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='ice cream';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='nuts';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 5 week) AND name='oranges';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='garlic press';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='shelves';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='pots';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='plants';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='yellow zip bags';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='kidney beans';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='metal scrub';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='dish soap';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='toilet paper';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='fruit';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='smoked salmon';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='zip loc bags';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='kitchen paper';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='frozen fish empanada huevo';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='chicken breast';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='cream cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='almonds';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='walnuts';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='bread';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='not oranges';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='lemon';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='dill';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='fresh basil';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='salt for holiday apt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='dijon mustard';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='feta';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='lemons';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='bread';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='cream cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='vegetable salad';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='salmon';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='toothpaste for holiday apt guest bath';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='dish soap';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='jam replace holiday appt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='ground beef';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='tin tomatoes small';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='pasta';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 6 week) AND name='eggs';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='pasta cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='smoked salmon';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='long life milk pack';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='olive oil';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='ice';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='hummus';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='milk fresh';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='cheddar';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='gin';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='edam cheese';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='cherry tomat';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='onions any';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='carrots';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='cabbage';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='bell peppers';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='cucumber';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='vegetables courgette aubergine';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='laundry detergent';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='microwave popcorn';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='breaded frozen fish mercadona';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='frozen shrimp';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='cupboard juice for holiday apt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='wine';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='frozen pizza';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='lemons';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='pork loin carniceria';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='walnuts';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='minced beef';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='chicken';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='espresso coffee';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='cucumber';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='cherry tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='pasta';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='mayonnaise';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='salad cheese supersol';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='milk supersol';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='sun dried tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='picture frame';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='grater';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 7 week) AND name='eggs';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='tahini they have aldi otherwise ignore';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='greek yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='sweetcorn tin';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='chickpeas';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='nectarines whatever fruit cheapest and works with yogurt';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='spinach';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='onions';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='cucumbers';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='cherry tomat';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='bell peppers';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='eggplant';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='zucchini';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='bottled water';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='bay leaves laurels';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='spegetti';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='tomato puree';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='tomatoes tin enteropelado';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='chili cayendo';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='rosemary romero';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='celery';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='ibuprofen';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='fenistil';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='antihistamine';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='mosquito repellent';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='bleach';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='nuts';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='shrimp';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='cooking butter';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='ground beef';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='fresh parsley';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='fruits';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='shallots';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='potatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='carrots';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='nice cream';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='toothpaste';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='avocado';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='backpacks';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='padel equipment';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 8 week) AND name='veg stock cubes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='paprika spicy sweet';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='oregano dried';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='egg pasta pref skinny ribbon shaped like tagliatelle';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='flour';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='vinegar';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='olive oil';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='flatbread';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='cabbage';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='mushrooms';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='cherry tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='nuts';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='bread';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='cherry tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='cucumber';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='cherry tomatoes';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='cranberry juice';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='eggs';
INSERT INTO items (weekid, productid) SELECT weeks.id, products.id FROM weeks, products WHERE start=DATE_SUB('2020-10-12',INTERVAL 9 week) AND name='potato';
